version: 2.1
workflows:
    lint-build-test:
        jobs:
            - lint-code
            - build-and-test:
                  requires:
                      - lint-code
jobs:
    lint-code:
        docker:
            - image: cimg/node:16.13.2
        steps:
            - checkout
            - run:
                  name: update npm
                  command: 'sudo npm install -g npm'

            - run:
                  name: install dependencies
                  command: sudo npm install

            - run:
                  name: lint code
                  command: npm run lint:check

    build-and-test:
        docker:
            - image: cimg/node:16.13.2
        steps:
            - checkout
            - run:
                  name: update npm
                  command: 'sudo npm install -g npm'

            - run:
                  name: install dependencies
                  command: sudo npm install

            - run:
                  name: run tests
                  command: npm test
